begin;
select set_config('request.jwt.claim.sub','1204ab25-7433-43a5-80e1-7a66b2eee057',true);
update public.artist_projects set status='archived' where id='96a9335d-12c3-4a58-b122-757c3adc82ac';
update public.artist_project_files set kind='demo',expires_at=now()+interval '1 day' where id='34fb4134-8c1e-4f13-a36d-914535d45dec';
update public.studio_bookings set status='cancelled' where id='9e76ee44-6f2c-4717-b213-44bfa29b9c7d';
insert into public.artist_career_profiles(user_id,artist_name,genres,goal_12_months) values(auth.uid(),'','','') on conflict(user_id) do update set artist_name='',genres='',goal_12_months='';
insert into private.artist_career_stage_state(user_id,stage_index) values(auth.uid(),1) on conflict(user_id) do update set stage_index=1;
do $$ declare pid uuid:=gen_random_uuid();r jsonb;begin
if exists(select 1 from public.artist_projects where user_id=auth.uid() and status<>'archived') then raise exception 'Unexpected active projects; fixture-only stage test stopped';end if;
r:=public.artist_career_progress();if r->>'stage'<>'join' then raise exception 'Join gate';end if;
update public.artist_career_profiles set artist_name='Test',genres='Reggae',goal_12_months='Release one single' where user_id=auth.uid();
r:=public.artist_career_progress();if r->>'stage'<>'discover' then raise exception 'Discover gate';end if;
insert into public.artist_projects(id,user_id,title,kind,status) values(pid,auth.uid(),'Disposable empty stage test','single','active');
r:=public.artist_career_progress();if r->>'stage'<>'plan' then raise exception 'Plan gate';end if;
update public.artist_projects set status='active' where id='96a9335d-12c3-4a58-b122-757c3adc82ac';
r:=public.artist_career_progress();if r->>'stage'<>'create' then raise exception 'Create gate';end if;
update public.studio_bookings set status='confirmed' where id='9e76ee44-6f2c-4717-b213-44bfa29b9c7d';
r:=public.artist_career_progress();if r->>'stage'<>'produce' then raise exception 'Produce gate';end if;
update public.artist_project_files set kind='master' where id='34fb4134-8c1e-4f13-a36d-914535d45dec';
r:=public.artist_career_progress();if r->>'stage'<>'prepare' then raise exception 'Prepare gate';end if;
update public.artist_project_files set expires_at=now()-interval '1 second' where id='34fb4134-8c1e-4f13-a36d-914535d45dec';
begin perform public.record_artist_delivery_collection('34fb4134-8c1e-4f13-a36d-914535d45dec');raise exception 'Expired collection allowed';exception when insufficient_privilege then null;end;
update public.artist_project_files set expires_at=now()+interval '1 day' where id='34fb4134-8c1e-4f13-a36d-914535d45dec';
perform public.record_artist_delivery_collection('34fb4134-8c1e-4f13-a36d-914535d45dec');
r:=public.artist_career_progress();if r->>'stage'<>'release' then raise exception 'Release gate';end if;
update public.artist_projects set status='released' where id=pid;
r:=public.artist_career_progress();if r->>'stage'<>'grow' then raise exception 'Grow gate';end if;
end;$$;
rollback;