begin;
update public.artist_projects set status='active' where id='96a9335d-12c3-4a58-b122-757c3adc82ac';
update public.artist_project_files set expires_at=now()+interval '1 day' where id='34fb4134-8c1e-4f13-a36d-914535d45dec';
update public.studio_bookings set status='confirmed' where id='9e76ee44-6f2c-4717-b213-44bfa29b9c7d';
insert into public.artist_career_profiles(user_id,artist_name,genres,goal_12_months) values('1204ab25-7433-43a5-80e1-7a66b2eee057','','','') on conflict(user_id) do update set artist_name='',genres='',goal_12_months='';
insert into private.artist_career_stage_state(user_id,stage_index) values('1204ab25-7433-43a5-80e1-7a66b2eee057',1) on conflict(user_id) do update set stage_index=1;
select set_config('request.jwt.claim.sub','1204ab25-7433-43a5-80e1-7a66b2eee057',true);set local role authenticated;
do $$ declare r jsonb;begin
r:=public.artist_career_progress();if r->>'stage'<>'join' then raise exception 'Skipped incomplete identity gate';end if;
update public.artist_career_profiles set artist_name='Disposable test',genres='Reggae',goal_12_months='Release one single' where user_id=auth.uid();
r:=public.artist_career_progress();if r->>'stage'<>'prepare' then raise exception 'Expected prepare before collection: %',r;end if;
perform public.record_artist_delivery_collection('34fb4134-8c1e-4f13-a36d-914535d45dec');
perform public.record_artist_delivery_collection('34fb4134-8c1e-4f13-a36d-914535d45dec');
if (select count(*) from public.artist_delivery_collections where file_id='34fb4134-8c1e-4f13-a36d-914535d45dec' and user_id=auth.uid())<>1 then raise exception 'Collection not idempotent';end if;
r:=public.artist_career_progress();if r->>'stage'<>'release' then raise exception 'Collection gate failed';end if;
update public.artist_projects set status='released' where id='96a9335d-12c3-4a58-b122-757c3adc82ac';
r:=public.artist_career_progress();if r->>'stage'<>'grow' then raise exception 'Release gate failed';end if;
update public.artist_career_profiles set genres='' where user_id=auth.uid();
r:=public.artist_career_progress();if r->>'stage'<>'grow' or r->>'evidenced_stage'<>'join' or not (r->>'held')::boolean then raise exception 'Historical stage regressed';end if;
end;$$;
reset role;
update public.app_memberships set artist_member_enabled=true where user_id='8da3fa1f-10ef-4fac-8294-279e6a9e61b1';
select set_config('request.jwt.claim.sub','8da3fa1f-10ef-4fac-8294-279e6a9e61b1',true);set local role authenticated;
do $$ begin
perform public.artist_career_progress();
begin perform public.artist_career_progress('1204ab25-7433-43a5-80e1-7a66b2eee057');raise exception 'Cross-account progression permitted';exception when insufficient_privilege then null;end;
begin perform public.record_artist_delivery_collection('34fb4134-8c1e-4f13-a36d-914535d45dec');raise exception 'Cross-account collection permitted';exception when insufficient_privilege then null;end;
end;$$;
reset role;update public.app_memberships set artist_member_enabled=false where user_id='8da3fa1f-10ef-4fac-8294-279e6a9e61b1';set local role authenticated;
do $$ begin begin perform public.artist_career_progress();raise exception 'Business-only progression permitted';exception when insufficient_privilege then null;end;end;$$;
rollback;