begin;
update public.app_memberships set access_status='active',payment_status='comped',artist_member_enabled=true,deleted_at=null,expires_at=null where user_id='8da3fa1f-10ef-4fac-8294-279e6a9e61b1';
create temporary table vault_fixture(beat uuid,request uuid,invoice uuid);
insert into public.studio_instrumentals(title,lease_price,licence_terms,master_filename,preview_filename) values('Disposable vault regression',150,'Test-only nonexclusive licence terms; no actual rights granted.','master.wav','preview.mp3');
insert into vault_fixture(beat) select id from public.studio_instrumentals where title='Disposable vault regression';
insert into storage.objects(bucket_id,name) select 'studio-instrumentals',beat||'/master/master.wav' from vault_fixture union all select 'studio-instrumentals',beat||'/preview/preview.mp3' from vault_fixture;
update public.studio_instrumentals set published=true where id=(select beat from vault_fixture);
grant select,update on vault_fixture to authenticated;
select set_config('request.jwt.claim.sub','8da3fa1f-10ef-4fac-8294-279e6a9e61b1',true);
set local role authenticated;
update vault_fixture set request=public.request_instrumental_lease(beat,'Disposable request');
do $test$ declare b uuid;begin select beat into b from vault_fixture;
if not private.vault_asset_access(b||'/preview/preview.mp3',false) or private.vault_asset_access(b||'/master/master.wav',false) then raise exception 'Preview/master gate failed';end if;
begin perform public.request_instrumental_lease(b,'duplicate');raise exception 'Duplicate request allowed';exception when unique_violation then null;end;
begin perform public.decide_instrumental_lease((select request from vault_fixture),'approve');raise exception 'Artist approved own request';exception when insufficient_privilege then null;end;
end $test$;
reset role;
select set_config('request.jwt.claim.sub','1204ab25-7433-43a5-80e1-7a66b2eee057',true);
set local role authenticated;
update vault_fixture set invoice=public.decide_instrumental_lease(request,'approve');
do $test$ begin
if public.decide_instrumental_lease((select request from vault_fixture),'approve')<>(select invoice from vault_fixture) then raise exception 'Approval retry created another invoice';end if;
if not exists(select 1 from public.documents d where d.id=(select invoice from vault_fixture) and d.doc_number like 'INV-%' and d.total=150 and d.deposit_pct=100) then raise exception 'Shared invoice allocator/price mismatch';end if;
begin perform public.decide_instrumental_lease((select request from vault_fixture),'release');raise exception 'Unpaid master released';exception when raise_exception then if sqlerrm='Unpaid master released' then raise;end if;end;
perform public.record_invoice_payment((select invoice from vault_fixture),'payment',150,'cash',(now() at time zone 'America/Barbados')::date,'','',null,'a121fc66-8d50-4ddb-b6ed-529609bba229');
perform public.record_invoice_payment((select invoice from vault_fixture),'payment',150,'cash',(now() at time zone 'America/Barbados')::date,'','',null,'a121fc66-8d50-4ddb-b6ed-529609bba229');
perform public.decide_instrumental_lease((select request from vault_fixture),'release');
end $test$;
reset role;
select set_config('request.jwt.claim.sub','8da3fa1f-10ef-4fac-8294-279e6a9e61b1',true);
set local role authenticated;
do $test$ begin if not private.vault_asset_access((select beat||'/master/master.wav' from vault_fixture),false) then raise exception 'Paid released master blocked';end if;end $test$;
reset role;
reset role;
do $test$ declare n bigint;begin
select count(*) into n from public.studio_notifications where body like 'Disposable vault regression.%';
if n<>6 then raise exception 'Expected request/approve/release for artist and Owner, got %',n;end if;
update public.studio_instrumental_requests set status=status where id=(select request from vault_fixture);
if (select count(*) from public.studio_notifications where body like 'Disposable vault regression.%')<>n then raise exception 'No-op duplicated';end if;
if (select count(*) from public.studio_notifications where event_id in(select id from public.payments where document_id=(select invoice from vault_fixture)))<>2 then raise exception 'Payment retry/recipient count';end if;
end $test$;
select set_config('request.jwt.claim.sub','1204ab25-7433-43a5-80e1-7a66b2eee057',true);
set local role authenticated;
select public.record_invoice_payment((select invoice from vault_fixture),'refund',25,'cash',(now() at time zone 'America/Barbados')::date,'','Test refund',(select id from public.payments where document_id=(select invoice from vault_fixture) and kind='payment'),gen_random_uuid());
select public.record_invoice_payment((select invoice from vault_fixture),'correction',25,'manual',(now() at time zone 'America/Barbados')::date,'','Test correction',(select id from public.payments where document_id=(select invoice from vault_fixture) and kind='payment'),gen_random_uuid());
reset role;
do $test$ begin
if (select count(*) from public.studio_notifications where event_id in(select id from public.payments where document_id=(select invoice from vault_fixture)))<>6 then raise exception 'Refund/correction recipients';end if;
end $test$;
select set_config('request.jwt.claim.sub','8da3fa1f-10ef-4fac-8294-279e6a9e61b1',true);
set local role authenticated;
do $test$ begin
if exists(select 1 from public.studio_notifications where user_id<>auth.uid()) then raise exception 'Inbox leak';end if;
if (select count(*) from public.studio_notifications where body like 'Disposable vault regression.%')<>3 then raise exception 'Member vault alerts';end if;
if exists(select 1 from public.studio_notifications where action_kind='payments') then raise exception 'Member owner payment destination';end if;
end $test$;
reset role;
rollback;
select 'PASS vault lifecycle, no-op/retry suppression, recorded payment/refund/correction recipients, member isolation; rolled back' result;